[project]
authors = [
  "Georgios Delkos <georgios.delkos@ourovoros.io>",
  "Henry Baldwin <henry@stork.xyz>",
]
entry = "main.sw"
license = "Apache-2.0"
name = "stork"

[dependencies]
stork_sway_sdk = { path = "../../../../sdks/fuel/stork-sway-sdk" }
signed_int = "0.26.1"
src5 = "0.8.1"

[proxy]
enabled = true
